import 'package:appnike/database/users/adress/adress.database.dart';
import 'package:appnike/database/users/credit_card/credit_card.database.dart';
import 'package:appnike/domain/user/gender.enum.dart';
import 'package:appnike/domain/user/user_example.dart';

List<User> usersDB = [
  User(
      id: 1,
      firstName: "John",
      lastName: "Doe",
      document: "123456789",
      email: "john.doe@example.com",
      phone: 5551234567,
      gender: Gender.male,
      birth: DateTime(1990, 4, 15),
      adress: addressesDB[0],
      creditCard: creditCardsDB[0],
      isPremium: true,
      image: "https://xsgames.co/randomusers/assets/avatars/male/8.jpg"),
  User(
      id: 2,
      firstName: "Jane",
      lastName: "Smith",
      document: "987654321",
      email: "jane.smith@example.com",
      phone: 5559876543,
      gender: Gender.female,
      birth: DateTime(1985, 6, 10),
      adress: addressesDB[1],
      creditCard: creditCardsDB[1],
      isPremium: false,
      image: "https://xsgames.co/randomusers/assets/avatars/female/67.jpg"),
  User(
      id: 3,
      firstName: "Robert",
      lastName: "Johnson",
      document: "123987456",
      email: "robert.johnson@example.com",
      phone: 5556547891,
      gender: Gender.male,
      birth: DateTime(1975, 8, 22),
      adress: addressesDB[2],
      creditCard: creditCardsDB[2],
      isPremium: true,
      image: "https://xsgames.co/randomusers/assets/avatars/male/16.jpg"),
  User(
      id: 4,
      firstName: "Emily",
      lastName: "Davis",
      document: "789456123",
      email: "emily.davis@example.com",
      phone: 5553216549,
      gender: Gender.female,
      birth: DateTime(1995, 12, 3),
      adress: addressesDB[3],
      creditCard: creditCardsDB[3],
      isPremium: false,
      image: "https://xsgames.co/randomusers/assets/avatars/female/11.jpg"),
  User(
      id: 5,
      firstName: "Michael",
      lastName: "Brown",
      document: "654321789",
      email: "michael.brown@example.com",
      phone: 5557893210,
      gender: Gender.male,
      birth: DateTime(2000, 2, 14),
      adress: addressesDB[4],
      creditCard: creditCardsDB[4],
      isPremium: true,
      image: "https://xsgames.co/randomusers/assets/avatars/male/4.jpg"),
];
